### ISSUE TITLE
Input should be added to the Context automatically.

### ISSUE THREAD

**Issue by redvex** [nibble-4bits/aws-local-stepfunctions#80]
Step functions allows us to refer to the input using the context Object. Although the library allows me to specify the context, would be nice if the input would be added automatically to the context:

## Step to reproduce

```
import { StateMachine } from 'aws-local-stepfunctions';

const machineDefinition = JSON.parse(JSON.stringify({
  StartAt: 'FilterInput',
  States: {
    FilterInput: {
      Type: 'Pass',
      Parameters: {
        'foo.$': '$$.Execution.Input.MyObject.foo'
      }, 
      End: true
    }
  },
}));

test('OK', async () => {
  // GIVEN
  const myInput = {
    MyObject: {
      foo: 'bar'
    }
  };

  // WHEN
  const stateMachine = new StateMachine(machineDefinition);
  const execution = stateMachine.run(myInput, {
    // context: {
    //   Execution: {
    //     Input: myInput
    //   }
    // }
  });
  const result = await execution.result;
  console.log(result);

  // THEN
  expect(result).toStrictEqual({ foo: 'bar' });
});
```

## Desired outcome

`$$.Execution.Input` should point to the stateMachine run input.

## Error

```
Cause:
    States.Runtime: Path expression '$$.Execution.Input.MyObject.foo' does not point to a value
```

## Workaround

To make it work, I can manually build the `context` object and pass to the stateMachine run method.

**Comment by nibble-4bits** [comment]
Hi @redvex, this feature has been released in [v1.3.0](https://github.com/nibble-4bits/aws-local-stepfunctions/releases/tag/v1.3.0)
