### ISSUE TITLE
Feature Request: override/disable wait on retry

### ISSUE THREAD

**Issue by mikicho** [nibble-4bits/aws-local-stepfunctions#84]
Thanks for this great lib!

We want to test the retry policy without waiting x seconds for each iteration. Is it possible to add an option to override the `IntervalSeconds` property?

We can change this value in the test code as a workaround, but it would be fragile.

**Comment by nibble-4bits** [comment]
Hi @mikicho,

Thanks for reaching out and suggesting this feature. I think it makes sense to have this kind of override as an option, especially for testing scenarios, such as yours. I'll add it to the lib.

**Comment by nibble-4bits** [comment]
@mikicho, this feature has been released in [v1.3.0](https://github.com/nibble-4bits/aws-local-stepfunctions/releases/tag/v1.3.0)
